name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: AquaHyperOS ${{ github.ref_name }}
        body_path: RELEASE_26W40F.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
